// src/app/blog/_components/BlogPostTemplate.tsx
'use client'

import { useEffect, useRef, useState } from 'react'
import { cn } from '@/lib/utils/utils'
import BaseContainer from '@/components/layout/container/base-container'
import { StackVertical } from '@/components/layout/layout-stack/layout-stack'
import { IndividualPageFooter } from '@/components/layout/footer/IndividualPageFooter'
import Text from '@/components/ui/text/text'
import { ContentPageHeader } from '@/components/layout/page-header/ContentPageHeader'

interface BlogPostTemplateProps {
    title: string
    date: string
    readingTime: string
    slug?: string
    themes?: string[]
    children: React.ReactNode
    className?: string
    articleId?: string
    containerSize?: 'sm' | 'md' | 'lg' | 'xl' | 'full'
    aside?: React.ReactNode
    mobileSectionBar?: React.ReactNode
    rightRail?: React.ReactNode
    articleShellClassName?: string
}

export function BlogPostTemplate({
    title,
    date,
    readingTime,
    slug,
    themes = [],
    children,
    className,
    articleId,
    containerSize = 'md',
    aside,
    mobileSectionBar,
    rightRail,
    articleShellClassName,
}: BlogPostTemplateProps) {
    const [readCount, setReadCount] = useState<number | null>(null)
    const hasRecordedReadRef = useRef(false)

    useEffect(() => {
        if (!slug || hasRecordedReadRef.current) return

        hasRecordedReadRef.current = true

        const recordRead = async () => {
            try {
                const response = await fetch('/api/blog/read-count', {
                    method: 'POST',
                    headers: {
                        'Content-Type': 'application/json',
                    },
                    body: JSON.stringify({ slug }),
                })
                const data = await response.json()

                if (response.ok && typeof data.count === 'number') {
                    setReadCount(data.count)
                }
            } catch (error) {
                console.error('Could not record blog read count:', error)
            }
        }

        recordRead()
    }, [slug])

    return (
        <div className="relative w-full">
            <BaseContainer size={containerSize} paddingX="md" paddingY="lg">
                <StackVertical gap="md">
                    <ContentPageHeader
                        title={title}
                        breadcrumbs={[
                            { href: '/', label: 'Home', emoji: '🐶' },
                            { href: '/journal', label: 'Journal' },
                            { label: title }
                        ]}
                        showPrideBadge={false}
                    >
                        <div className="flex flex-wrap items-center gap-x-2 gap-y-1.5">
                            <Text variant="muted" size="sm">
                                {date} | {readingTime}
                            </Text>
                            {readCount !== null && (
                                <>
                                    <span className="text-muted-foreground/30">•</span>
                                    <Text variant="muted" size="sm">
                                        {readCount.toLocaleString()} reads
                                    </Text>
                                </>
                            )}
                            {themes.map((theme) => (
                                <div key={theme} className="flex items-center gap-2">
                                    <span className="text-muted-foreground/30">•</span>
                                    <Text size="sm" weight="medium" className="pride-text lowercase">
                                        {theme}
                                    </Text>
                                </div>
                            ))}
                        </div>

                    </ContentPageHeader>

                    {aside || rightRail ? (
                        <div className={cn(
                            "grid gap-6 xl:gap-8 xl:grid-cols-[minmax(0,1fr)_72px]",
                            articleShellClassName
                        )}>
                                <article id={articleId} className="relative">
                                    {/* Desktop sidebar - absolutely positioned to the left */}
                                    <div className="hidden xl:block absolute right-full mr-8 2xl:mr-12 top-0 bottom-0 pointer-events-none">
                                        <div className="sticky top-1/2 -translate-y-1/2 pointer-events-auto flex justify-end">
                                            {aside}
                                        </div>
                                    </div>

                                    {/* Mobile sticky section bar */}
                                    {mobileSectionBar && (
                                        <div className="xl:hidden">
                                            {mobileSectionBar}
                                        </div>
                                    )}

                                    <div 
                                        id="blog-content-body" 
                                        className={cn("prose max-w-none pb-24 pt-2 xl:pb-0 dark:prose-invert relative", className)}
                                    >
                                        {children}
                                    </div>
                                </article>
                                <div>{rightRail}</div>
                            </div>
                    ) : (
                        <article id={articleId}>
                            <div 
                                id="blog-content-body" 
                                className={cn("prose max-w-none pt-2 dark:prose-invert relative", className)}
                            >
                                {children}
                            </div>
                        </article>
                    )}

                </StackVertical>
            </BaseContainer>

            <IndividualPageFooter parentPageName='Journal' />
        </div>
    )
}

// apps/web-sveltekit/src/lib/components/BlogPostTemplate.svelte
<script lang="ts">
  import { onMount } from 'svelte';
  import ArticleLineRail from './ArticleLineRail.svelte';
  import ArticleSectionPreview from './ArticleSectionPreview.svelte';
  import ArticleSectionPreviewMobile from './ArticleSectionPreviewMobile.svelte';
  import ThemeToggle from './ThemeToggle.svelte';
  import SiteFooter from './SiteFooter.svelte';
  import BaseContainer from './BaseContainer.svelte';
  import StackVertical from './StackVertical.svelte';

  export let title: string;
  export let date: string;
  export let readingTime: string;
  export let slug = '';
  export let themes: string[] = [];
  export let contentClassName = '';

  let readCount: number | null = null;

  async function recordRead() {
    if (!slug) return;
    try {
      const response = await fetch('/api/blog/read-count', {
        method: 'POST',
        headers: {
          'Content-Type': 'application/json'
        },
        body: JSON.stringify({ slug })
      });
      const data = await response.json();
      if (response.ok && typeof data.count === 'number') {
        readCount = data.count;
      }
    } catch (error) {
      console.error('Could not record blog read count:', error);
    }
  }

  onMount(() => {
    recordRead();
  });
</script>

<div class="relative w-full">
  <BaseContainer size="xl" paddingX="md" paddingY="lg">
    <StackVertical gap="md">
      <!-- Breadcrumb Header -->
      <section class="page-intro">
        <div class="section-header-top">
          <nav class="breadcrumb" aria-label="Breadcrumb">
            <a href="/" class="breadcrumb-home">
              <img src="/icon.svg" alt="" width="18" height="18" aria-hidden="true" />
              Home
            </a>
            <span aria-hidden="true">/</span>
            <a href="/journal">Journal</a>
            <span aria-hidden="true">/</span>
            <span class="truncate max-w-[150px] sm:max-w-[240px] md:max-w-[350px] lg:max-w-[450px] inline-block align-bottom" title={title}>{title}</span>
          </nav>
          <ThemeToggle />
        </div>

        <div class="section-title-block space-y-2 mt-4">
          <h1 class="font-sans font-bold text-2xl sm:text-3xl md:text-3xl lg:text-4xl text-slate-900 dark:text-white mt-0 mb-4">
            {title}
          </h1>
          <div class="flex flex-wrap items-center gap-x-2 gap-y-1.5 font-mono text-xs text-muted-foreground">
            <span>{date} | {readingTime}</span>
            {#if readCount !== null}
              <span class="text-muted-foreground/30">•</span>
              <span>{readCount.toLocaleString()} reads</span>
            {/if}
            {#each themes as theme}
              <span class="text-muted-foreground/30">•</span>
              <span class="pride-text lowercase font-medium">{theme}</span>
            {/each}
          </div>
        </div>
      </section>

      <!-- Main Article Area Grid -->
      <div class="blog-post-shell">
        <article id="content" class="relative">
          <!-- Desktop sidebar - absolutely positioned to the left -->
          <div class="hidden xl:block absolute right-full mr-8 2xl:mr-12 top-0 bottom-0 pointer-events-none">
            <div class="sticky top-1/2 -translate-y-1/2 pointer-events-auto flex justify-end">
              <ArticleSectionPreview articleId="content" />
            </div>
          </div>

          <!-- Mobile sticky section bar -->
          <div class="xl:hidden">
            <ArticleSectionPreviewMobile articleId="content" />
          </div>

          <div
            id="blog-content-body"
            class="prose prose-panel max-w-none pb-24 pt-2 xl:pb-0 dark:prose-invert relative {contentClassName}"
          >
            <slot />
          </div>
        </article>

        <ArticleLineRail articleId="content" />
      </div>
    </StackVertical>
  </BaseContainer>

  <SiteFooter color="blue" />
</div>
