// src/app/draw/_components/DrawPromptForm.tsx
'use client'

import { FormEvent, useState } from 'react'
import { sansFont } from '@/styles/fonts/fonts'
import { cn } from '@/lib/utils/utils'
import { Button } from '@/components/ui/primitives/button'
import { AttachmentPreviewGrid } from '@/components/ui/attachments/AttachmentPreviewGrid'
import { AttachmentUploadButton } from '@/components/ui/attachments/AttachmentUploadButton'
import { MAX_ATTACHMENT_COUNT } from '@/lib/images/attachment-limits'
import { prepareImageForUpload } from '@/lib/images/prepare-upload'

interface DrawPromptFormProps {
  onSubmit: (payload: { author: string; body: string; character: string; media: string; imageUrls: string[] }) => Promise<void>
  isPending: boolean
  isCooldownActive: boolean
  cooldownLabel: string
  showNotification: (msg: string) => void
}

export function DrawPromptForm({
  onSubmit,
  isPending,
  isCooldownActive,
  cooldownLabel,
  showNotification
}: DrawPromptFormProps) {
  const [author, setAuthor] = useState('')
  const [body, setBody] = useState('')
  const [imageUrls, setImageUrls] = useState<string[]>([])

  const handleImageUpload = async (file: File) => {
    try {
      const url = await prepareImageForUpload(file)
      setImageUrls(prev => prev.length >= MAX_ATTACHMENT_COUNT ? prev : [...prev, url])
    } catch (error) {
      showNotification(error instanceof Error ? error.message : 'Could not attach image.')
    }
  }

  const handleSubmit = async (event: FormEvent<HTMLFormElement>) => {
    event.preventDefault()
    const trimmedBody = body.trim()
    if (!trimmedBody || isCooldownActive) return

    try {
      await onSubmit({
        author: author.trim(),
        body: trimmedBody,
        character: '',
        media: '',
        imageUrls
      })
      setBody('')
      setImageUrls([])
    } catch (e) {
      // Parent handles showing error
    }
  }

  return (
    <form 
      className="bg-white/40 dark:bg-slate-950/20 rounded-xl border border-slate-200/50 dark:border-slate-850/50 shadow-sm flex flex-col overflow-hidden pride-focus-within-glow" 
      onSubmit={handleSubmit}
    >
      {/* Top: Alias Field */}
      <div className="border-b border-slate-100 dark:border-slate-900 px-4 py-3 bg-slate-50/20 dark:bg-slate-950/20">
        <input
          type="text"
          value={author}
          onChange={(event) => setAuthor(event.target.value)}
          placeholder="Your alias (optional)"
          className={cn(
            sansFont.className,
            "w-full bg-transparent text-sm font-semibold text-slate-800 placeholder:text-muted-foreground/60 focus:outline-none dark:text-slate-100"
          )}
        />
      </div>

      {/* Middle: Prompt Field */}
      <div className="px-4 py-2">
        <textarea
          value={body}
          onChange={(event) => setBody(event.target.value)}
          onInput={(e) => {
            e.currentTarget.style.height = 'auto';
            e.currentTarget.style.height = `${e.currentTarget.scrollHeight}px`;
          }}
          placeholder="Suggest a drawing prompt... (describe characters, actions, or series here)"
          rows={1}
          className={cn(
            sansFont.className,
            "w-full bg-transparent py-2 text-base text-slate-900 placeholder:text-slate-400 focus:outline-none dark:text-slate-100 dark:placeholder:text-slate-600 resize-none overflow-hidden min-h-[100px]"
          )}
        />
      </div>

      {/* Attachment thumbnails */}
      <AttachmentPreviewGrid
        urls={imageUrls}
        onRemove={(index) => setImageUrls(prev => prev.filter((_, itemIndex) => itemIndex !== index))}
        className="px-4 pb-3"
      />

      {/* Bottom: Action Bar */}
      <div className="flex flex-col sm:flex-row sm:items-center sm:justify-between gap-4 border-t border-slate-100 dark:border-slate-900 px-4 py-3.5 bg-slate-50/20 dark:bg-slate-950/20">
        <div className="flex flex-wrap items-center gap-x-5 gap-y-3">
          <AttachmentUploadButton
            onFiles={(files) => files.forEach(file => handleImageUpload(file))}
            iconSize={13}
            className={cn(sansFont.className, 'gap-1.5 text-xs font-semibold')}
            accent="violet"
          >
            Add images
          </AttachmentUploadButton>
        </div>
        
        <Button 
          type="submit" 
          size="sm"
          disabled={!body.trim() || isPending || isCooldownActive}
          className="w-full sm:w-auto h-9 px-4.5 text-xs font-semibold rounded-md pride-button"
          title={isCooldownActive ? `You can send another prompt in ${cooldownLabel}` : undefined}
        >
          {isCooldownActive ? cooldownLabel : 'Send prompt'}
        </Button>
      </div>
    </form>
  )
}

// apps/web-sveltekit/src/lib/components/DrawPromptForm.svelte
<script lang="ts">
  import AttachmentPreviewGrid from './AttachmentPreviewGrid.svelte';
  import AttachmentUploadButton from './AttachmentUploadButton.svelte';
  import { MAX_ATTACHMENT_COUNT } from '$lib/images/attachment-limits';
  import { prepareImageForUpload } from '$lib/images/prepare-upload';

  export let onSubmit: (payload: { author: string; body: string; character: string; media: string; imageUrls: string[] }) => Promise<void>;
  export let isPending = false;
  export let isCooldownActive = false;
  export let cooldownLabel = '';
  export let showNotification: (msg: string) => void;

  let author = '';
  let body = '';
  let imageUrls: string[] = [];

  async function handleImageUpload(file: File) {
    try {
      const url = await prepareImageForUpload(file);
      imageUrls = imageUrls.length >= MAX_ATTACHMENT_COUNT ? imageUrls : [...imageUrls, url];
    } catch (error) {
      showNotification(error instanceof Error ? error.message : 'Could not attach image.');
    }
  }

  async function handleSubmit(event: Event) {
    event.preventDefault();
    const trimmedBody = body.trim();
    if (!trimmedBody || isCooldownActive) return;

    try {
      await onSubmit({
        author: author.trim(),
        body: trimmedBody,
        character: '',
        media: '',
        imageUrls
      });
      body = '';
      imageUrls = [];
    } catch (e) {
      // Parent handles showing error
    }
  }

  function handleInput(event: Event) {
    const textarea = event.target as HTMLTextAreaElement;
    textarea.style.height = 'auto';
    textarea.style.height = `${textarea.scrollHeight}px`;
  }
</script>

<form 
  class="bg-white/40 dark:bg-slate-950/20 rounded-xl border border-slate-200/50 dark:border-slate-850/50 shadow-sm flex flex-col text-left overflow-hidden pride-focus-within-glow" 
  on:submit={handleSubmit}
>
  <!-- Top: Alias Field -->
  <div class="border-b border-slate-100 dark:border-slate-900 px-4 py-3 bg-slate-50/20 dark:bg-slate-950/20 rounded-t-xl">
    <input
      type="text"
      bind:value={author}
      placeholder="Your alias (optional)"
      class="w-full bg-transparent text-sm font-semibold text-slate-800 placeholder:text-muted-foreground/60 focus:outline-none dark:text-slate-100 font-sans"
    />
  </div>

  <!-- Middle: Prompt Field -->
  <div class="px-4 py-2">
    <textarea
      bind:value={body}
      on:input={handleInput}
      placeholder="Suggest a drawing prompt... (describe characters, actions, or series here)"
      rows={1}
      class="w-full bg-transparent py-2 text-base text-slate-900 placeholder:text-slate-400 focus:outline-none dark:text-slate-100 dark:placeholder:text-slate-600 resize-none overflow-hidden min-h-[100px] font-sans"
    />
  </div>

  <!-- Attachment thumbnails -->
  <AttachmentPreviewGrid
    urls={imageUrls}
    onRemove={(index) => (imageUrls = imageUrls.filter((_, itemIndex) => itemIndex !== index))}
    className="px-4 pb-3"
  />

  <!-- Bottom: Action Bar -->
  <div class="flex flex-col sm:flex-row sm:items-center sm:justify-between gap-4 border-t border-slate-100 dark:border-slate-900 px-4 py-3.5 bg-slate-50/20 dark:bg-slate-950/20 rounded-b-xl">
    <div class="flex flex-wrap items-center gap-x-5 gap-y-3">
      <AttachmentUploadButton
        onFiles={(files) => files.forEach(handleImageUpload)}
        iconSize={13}
        className="gap-1.5 text-xs font-semibold font-sans"
        accent="violet"
      >
        Add images
      </AttachmentUploadButton>
    </div>
    
    <button 
      type="submit" 
      disabled={!body.trim() || isPending || isCooldownActive}
      class="w-full sm:w-auto h-9 px-4.5 text-xs font-semibold rounded-md pride-button cursor-pointer disabled:opacity-50 font-sans"
      title={isCooldownActive ? `You can send another prompt in ${cooldownLabel}` : undefined}
    >
      {isCooldownActive ? cooldownLabel : 'Send prompt'}
    </button>
  </div>
</form>
