// src/components/layout/page-shell/SectionPageShell.tsx
import type { ReactNode } from 'react'
import BaseContainer from '@/components/layout/container/base-container'
import { SectionFooter } from '@/components/layout/footer/SectionFooter'
import { StackVertical } from '@/components/layout/layout-stack/layout-stack'
import { SectionPageHeader } from '@/components/layout/page-header/SectionPageHeader'

type ContainerSize = 'sm' | 'md' | 'lg' | 'xl' | 'full'
type StackGap = 'none' | 'xs' | 'sm' | 'md' | 'lg' | 'xl'

interface SectionPageShellProps {
	children: ReactNode
	title: string
	description: string
	currentLabel: string
	containerSize?: ContainerSize
	contentGap?: StackGap
	footerColor?: string
	showToTop?: boolean
}

export function SectionPageShell({
	children,
	title,
	description,
	currentLabel,
	containerSize = 'md',
	contentGap = 'lg',
	footerColor = 'blue',
	showToTop = false,
}: SectionPageShellProps) {
	return (
		<BaseContainer size={containerSize} paddingX="md" paddingY="lg">
			<StackVertical gap={contentGap}>
				<SectionPageHeader
					title={title}
					description={description}
					currentLabel={currentLabel}
				/>

				{children}
			</StackVertical>

			<SectionFooter color={footerColor} showToTop={showToTop} />
		</BaseContainer>
	)
}

// apps/web-sveltekit/src/lib/components/SectionPageShell.svelte
<script lang="ts">
  import BaseContainer from './BaseContainer.svelte';
  import StackVertical from './StackVertical.svelte';
  import PageIntro from './PageIntro.svelte';
  import SiteFooter from './SiteFooter.svelte';

  export let title: string;
  export let description = '';
  export let currentLabel = '';
  export let containerSize: 'sm' | 'md' | 'lg' | 'xl' | '2xl' | '3xl' | 'full' = 'lg';
  export let contentGap: 'none' | 'xs' | 'sm' | 'md' | 'lg' | 'xl' = 'lg';
  export let footerColor = 'blue';
</script>

<BaseContainer size={containerSize} paddingX="md" paddingY="lg">
  <StackVertical gap={contentGap}>
    <PageIntro
      eyebrow={currentLabel}
      {title}
      {description}
    />

    <slot />
  </StackVertical>

  <SiteFooter color={footerColor} />
</BaseContainer>
