// apps/web-sveltekit/src/lib/components/ImageCropperModal.svelte
<script lang="ts">
  import { onMount, onDestroy, createEventDispatcher } from 'svelte';
  import { browser } from '$app/environment';
  import { ZoomIn, ZoomOut, X } from '@lucide/svelte';
  import { fade, scale } from 'svelte/transition';

  export let imageSrc: string;
  export let defaultAspectRatio: '3:4' | '16:9' | '1:1' | 'original' = '3:4';

  const dispatch = createEventDispatcher<{ close: void; crop: string }>();

  type CropAspectRatio = '3:4' | '16:9' | '1:1' | 'original';

  const ASPECT_RATIO_PRESETS: { key: CropAspectRatio; label: string }[] = [
    { key: '3:4', label: '3:4 cover' },
    { key: '16:9', label: '16:9 screen' },
    { key: '1:1', label: '1:1 square' },
    { key: 'original', label: 'original' },
  ];

  let aspectRatio: CropAspectRatio = defaultAspectRatio;
  let zoom = 1;
  let offsetX = 0;
  let offsetY = 0;
  let imgW = 0;
  let imgH = 0;
  let isLoading = true;
  let containerEl: HTMLDivElement;
  let containerW = 380;
  let containerH = 340;

  let isDragging = false;
  let dragStartX = 0;
  let dragStartY = 0;
  let dragOffsetStartX = 0;
  let dragOffsetStartY = 0;

  function portal(node: HTMLElement) {
    if (!browser) return {};
    document.body.appendChild(node);
    return {
      destroy() {
        node.remove();
      }
    };
  }

  $: arVal = imgW > 0
    ? aspectRatio === 'original' ? imgW / imgH
    : aspectRatio === '3:4' ? 0.75
    : aspectRatio === '16:9' ? 16 / 9
    : 1
    : 1;

  $: frameW = (() => {
    const maxW = containerW - 40;
    const maxH = containerH - 40;
    let fw = maxW;
    let fh = maxW / arVal;
    if (fh > maxH) { fh = maxH; fw = maxH * arVal; }
    return fw;
  })();

  $: frameH = (() => {
    const maxW = containerW - 40;
    const maxH = containerH - 40;
    let fw = maxW;
    let fh = maxW / arVal;
    if (fh > maxH) { fh = maxH; fw = maxH * arVal; }
    return fh;
  })();

  $: frameX = (containerW - frameW) / 2;
  $: frameY = (containerH - frameH) / 2;

  $: baseImgW = imgW > 0 ? imgW * Math.max(frameW / imgW, frameH / imgH) : 0;
  $: baseImgH = imgH > 0 ? imgH * Math.max(frameW / imgW, frameH / imgH) : 0;

  $: maxPanX = Math.max(0, (baseImgW * zoom - frameW) / 2);
  $: maxPanY = Math.max(0, (baseImgH * zoom - frameH) / 2);

  $: {
    offsetX = Math.max(-maxPanX, Math.min(maxPanX, offsetX));
    offsetY = Math.max(-maxPanY, Math.min(maxPanY, offsetY));
  }

  function loadImage() {
    isLoading = true;
    const img = new Image();
    img.onload = () => {
      imgW = img.naturalWidth;
      imgH = img.naturalHeight;
      isLoading = false;
      zoom = 1;
      offsetX = 0;
      offsetY = 0;
    };
    img.src = imageSrc;
  }

  function handleMouseDown(e: MouseEvent) {
    e.preventDefault();
    isDragging = true;
    dragStartX = e.clientX;
    dragStartY = e.clientY;
    dragOffsetStartX = offsetX;
    dragOffsetStartY = offsetY;
  }

  function handleTouchStart(e: TouchEvent) {
    if (e.touches.length === 1) {
      isDragging = true;
      dragStartX = e.touches[0].clientX;
      dragStartY = e.touches[0].clientY;
      dragOffsetStartX = offsetX;
      dragOffsetStartY = offsetY;
    }
  }

  function handleMouseMove(e: MouseEvent) {
    if (!isDragging) return;
    const dx = e.clientX - dragStartX;
    const dy = e.clientY - dragStartY;
    offsetX = Math.max(-maxPanX, Math.min(maxPanX, dragOffsetStartX + dx));
    offsetY = Math.max(-maxPanY, Math.min(maxPanY, dragOffsetStartY + dy));
  }

  function handleTouchMove(e: TouchEvent) {
    if (!isDragging || e.touches.length !== 1) return;
    e.preventDefault();
    const dx = e.touches[0].clientX - dragStartX;
    const dy = e.touches[0].clientY - dragStartY;
    offsetX = Math.max(-maxPanX, Math.min(maxPanX, dragOffsetStartX + dx));
    offsetY = Math.max(-maxPanY, Math.min(maxPanY, dragOffsetStartY + dy));
  }

  function handleMouseUp() { isDragging = false; }

  function handleWheel(e: WheelEvent) {
    e.preventDefault();
    const step = 0.05;
    zoom = Math.max(1, Math.min(3, parseFloat((zoom - e.deltaY * step * 0.01).toFixed(2))));
  }

  function handleSave() {
    if (!imgW || !frameW || !frameH) return;
    const canvas = document.createElement('canvas');
    const baseScale = Math.max(frameW / imgW, frameH / imgH);
    const sTotal = baseScale * zoom;
    const wOrig = frameW / sTotal;
    const hOrig = frameH / sTotal;
    const lOrig = imgW / 2 - (frameW / 2 + offsetX) / sTotal;
    const tOrig = imgH / 2 - (frameH / 2 + offsetY) / sTotal;
    const safeL = Math.max(0, Math.min(imgW - 1, lOrig));
    const safeT = Math.max(0, Math.min(imgH - 1, tOrig));
    const safeW = Math.max(1, Math.min(imgW - safeL, wOrig));
    const safeH = Math.max(1, Math.min(imgH - safeT, hOrig));
    const ar = safeW / safeH;
    let tw = ar >= 1 ? 800 : Math.round(800 * ar);
    let th = ar >= 1 ? Math.round(800 / ar) : 800;
    canvas.width = tw;
    canvas.height = th;
    const ctx = canvas.getContext('2d');
    if (!ctx) return;
    ctx.imageSmoothingEnabled = true;
    ctx.imageSmoothingQuality = 'high';
    const img = new Image();
    img.onload = () => {
      ctx.drawImage(img, safeL, safeT, safeW, safeH, 0, 0, tw, th);
      dispatch('crop', canvas.toDataURL('image/jpeg', 0.85));
      dispatch('close');
    };
    img.src = imageSrc;
  }

  let resizeObserver: ResizeObserver;

  onMount(() => {
    loadImage();
    document.body.style.overflow = 'hidden';
    resizeObserver = new ResizeObserver((entries) => {
      if (entries[0]) {
        containerW = entries[0].contentRect.width;
        containerH = entries[0].contentRect.height;
      }
    });
    if (containerEl) resizeObserver.observe(containerEl);
    window.addEventListener('mousemove', handleMouseMove);
    window.addEventListener('mouseup', handleMouseUp);
    window.addEventListener('touchmove', handleTouchMove, { passive: false });
    window.addEventListener('touchend', handleMouseUp);
  });

  onDestroy(() => {
    if (browser) {
      document.body.style.overflow = '';
      resizeObserver?.disconnect();
      window.removeEventListener('mousemove', handleMouseMove);
      window.removeEventListener('mouseup', handleMouseUp);
      window.removeEventListener('touchmove', handleTouchMove);
      window.removeEventListener('touchend', handleMouseUp);
    }
  });

  $: if (aspectRatio) { zoom = 1; offsetX = 0; offsetY = 0; }
</script>

<div use:portal class="cropper-overlay" transition:fade={{ duration: 180 }} on:click|self={() => dispatch('close')} role="dialog" aria-modal="true" tabindex="-1">
  <div class="cropper-modal" transition:scale={{ duration: 220, start: 0.95 }}>
    <!-- Header -->
    <div class="cropper-header">
      <span class="cropper-title">crop cover image</span>
      <button type="button" class="cropper-close" on:click={() => dispatch('close')}>
        <X size={16} />
      </button>
    </div>

    <!-- Workspace -->
    <div
      bind:this={containerEl}
      class="cropper-workspace"
      on:mousedown={handleMouseDown}
      on:touchstart={handleTouchStart}
      on:wheel={handleWheel}
      role="img"
      aria-label="Crop area"
    >
      {#if isLoading || !imgW}
        <div class="cropper-loading">
          <div class="cropper-spinner"></div>
          <span>loading cover...</span>
        </div>
      {:else}
        <!-- Image -->
        <img
          src={imageSrc}
          alt="Crop source"
          class="cropper-img"
          style="
            width: {baseImgW}px;
            height: {baseImgH}px;
            transform: translate({offsetX}px, {offsetY}px) scale({zoom});
            left: 50%;
            top: 50%;
            margin-left: {-baseImgW / 2}px;
            margin-top: {-baseImgH / 2}px;
          "
        />
        <!-- Overlays -->
        <div class="cropper-overlay-mask" style="left:0;top:0;width:{containerW}px;height:{frameY}px"></div>
        <div class="cropper-overlay-mask" style="left:0;top:{frameY + frameH}px;width:{containerW}px;bottom:0"></div>
        <div class="cropper-overlay-mask" style="left:0;top:{frameY}px;width:{frameX}px;height:{frameH}px"></div>
        <div class="cropper-overlay-mask" style="left:{frameX + frameW}px;top:{frameY}px;right:0;height:{frameH}px"></div>
        <!-- Crop frame -->
        <div class="cropper-frame" style="left:{frameX}px;top:{frameY}px;width:{frameW}px;height:{frameH}px">
          <div class="cropper-grid">
            {#each Array(9) as _, i}
              <div class="cropper-grid-cell"
                style="border-right: {i % 3 !== 2 ? '1px solid rgba(255,255,255,0.2)' : 'none'};
                       border-bottom: {i < 6 ? '1px solid rgba(255,255,255,0.2)' : 'none'}"
              ></div>
            {/each}
          </div>
        </div>
      {/if}
    </div>

    <!-- Controls -->
    {#if !isLoading && imgW}
      <div class="cropper-controls">
        <!-- Zoom -->
        <div class="cropper-zoom-row">
          <ZoomOut size={14} class="text-slate-400" />
          <input
            type="range" min="1" max="3" step="0.01"
            bind:value={zoom}
            class="cropper-zoom-slider"
          />
          <ZoomIn size={14} class="text-slate-400" />
          <span class="cropper-zoom-label">{Math.round(zoom * 100)}%</span>
        </div>

        <!-- Aspect ratio -->
        <div class="cropper-ar-section">
          <span class="cropper-ar-label">aspect ratio</span>
          <div class="cropper-ar-presets">
            {#each ASPECT_RATIO_PRESETS as preset}
              <button
                type="button"
                class="cropper-ar-btn"
                class:active={aspectRatio === preset.key}
                on:click={() => (aspectRatio = preset.key)}
              >{preset.label}</button>
            {/each}
          </div>
        </div>
      </div>
    {/if}

    <!-- Footer -->
    <div class="cropper-footer">
      <button type="button" class="cropper-btn cropper-btn-outline" on:click={() => dispatch('close')}>cancel</button>
      <button type="button" class="cropper-btn cropper-btn-primary" on:click={handleSave} disabled={isLoading || !imgW}>
        crop & save cover
      </button>
    </div>
  </div>
</div>

<style>
  .cropper-overlay {
    position: fixed;
    inset: 0;
    z-index: 50;
    display: flex;
    align-items: flex-start;
    justify-content: center;
    overflow-y: auto;
    background: hsl(222 47% 11% / 0.8);
    backdrop-filter: blur(4px);
    padding: 4rem 1rem 2rem;
  }

  .cropper-modal {
    position: relative;
    width: 100%;
    max-width: min(42rem, calc(100vw - 2rem));
    border-radius: 0.75rem;
    border: 1px solid hsl(var(--border) / 0.78);
    background: hsl(0 0% 100% / 0.98);
    padding: 1.125rem;
    box-shadow: 0 14px 48px hsl(222 47% 4% / 0.22);
    display: flex;
    flex-direction: column;
    gap: 0.9rem;
    z-index: 10;
  }

  :global(.dark) .cropper-modal {
    border-color: hsl(217 28% 28% / 0.9);
    background: hsl(222 30% 14% / 0.98);
    box-shadow: 0 18px 58px hsl(222 47% 3% / 0.4);
  }

  .cropper-header {
    display: flex;
    align-items: center;
    justify-content: space-between;
    border-bottom: 1px solid hsl(var(--border) / 0.5);
    padding-bottom: 0.75rem;
  }

  .cropper-title {
    font-size: 0.875rem;
    font-weight: 700;
    color: hsl(var(--foreground));
    font-family: var(--font-sans);
    text-transform: lowercase;
  }

  .cropper-close {
    color: hsl(var(--muted-foreground));
    cursor: pointer;
    background: none;
    border: none;
    display: flex;
    align-items: center;
    transition: color 0.15s;
  }
  .cropper-close:hover { color: hsl(var(--foreground)); }

  .cropper-workspace {
    position: relative;
    display: flex;
    align-items: center;
    justify-content: center;
    background:
      linear-gradient(45deg, hsl(220 12% 88%) 25%, transparent 25%),
      linear-gradient(-45deg, hsl(220 12% 88%) 25%, transparent 25%),
      linear-gradient(45deg, transparent 75%, hsl(220 12% 88%) 75%),
      linear-gradient(-45deg, transparent 75%, hsl(220 12% 88%) 75%),
      hsl(0 0% 96%);
    background-position: 0 0, 0 10px, 10px -10px, -10px 0;
    background-size: 20px 20px;
    border: 1px solid hsl(var(--border) / 0.65);
    border-radius: 0.5rem;
    height: min(52vh, 430px);
    min-height: 320px;
    width: 100%;
    overflow: hidden;
    cursor: move;
    touch-action: none;
    user-select: none;
  }

  :global(.dark) .cropper-workspace {
    background:
      linear-gradient(45deg, hsl(222 22% 20%) 25%, transparent 25%),
      linear-gradient(-45deg, hsl(222 22% 20%) 25%, transparent 25%),
      linear-gradient(45deg, transparent 75%, hsl(222 22% 20%) 75%),
      linear-gradient(-45deg, transparent 75%, hsl(222 22% 20%) 75%),
      hsl(222 24% 17%);
    background-position: 0 0, 0 10px, 10px -10px, -10px 0;
    background-size: 20px 20px;
    border-color: hsl(217 28% 30% / 0.85);
  }

  .cropper-loading {
    display: flex;
    flex-direction: column;
    align-items: center;
    gap: 0.5rem;
    pointer-events: none;
    font-size: 0.625rem;
    letter-spacing: 0.1em;
    text-transform: lowercase;
    color: hsl(var(--muted-foreground));
    font-family: var(--font-mono);
  }

  .cropper-spinner {
    width: 1.5rem;
    height: 1.5rem;
    border-radius: 50%;
    border: 2px solid hsl(var(--pride-glow-val));
    border-top-color: transparent;
    animation: spin 0.8s linear infinite;
  }

  @keyframes spin { to { transform: rotate(360deg); } }

  .cropper-img {
    position: absolute;
    pointer-events: none;
    user-select: none;
    max-width: none;
    max-height: none;
    transform-origin: center center;
  }

  .cropper-overlay-mask {
    position: absolute;
    background: hsl(220 16% 8% / 0.46);
    backdrop-filter: blur(0.5px);
    pointer-events: none;
  }

  .cropper-frame {
    position: absolute;
    border: 1px solid white;
    pointer-events: none;
    box-shadow: 0 0 0 1px rgba(0,0,0,0.3);
  }

  .cropper-grid {
    position: absolute;
    inset: 0;
    display: grid;
    grid-template-columns: repeat(3, 1fr);
    grid-template-rows: repeat(3, 1fr);
    pointer-events: none;
    opacity: 0.5;
  }

  .cropper-grid-cell { }

  .cropper-controls {
    display: flex;
    flex-direction: column;
    gap: 1rem;
    padding: 0.25rem 0;
  }

  .cropper-zoom-row {
    display: flex;
    align-items: center;
    gap: 0.75rem;
  }

  .cropper-zoom-slider {
    flex: 1;
    height: 4px;
    background: hsl(var(--border));
    border-radius: 9999px;
    appearance: none;
    cursor: pointer;
    accent-color: hsl(var(--pride-glow-val));
  }

  .cropper-zoom-label {
    font-size: 0.5625rem;
    color: hsl(var(--muted-foreground));
    font-family: var(--font-mono);
    width: 2rem;
    text-align: right;
  }

  .cropper-ar-section {
    display: flex;
    flex-direction: column;
    gap: 0.375rem;
  }

  .cropper-ar-label {
    font-size: 0.5625rem;
    text-transform: lowercase;
    letter-spacing: 0.1em;
    color: hsl(var(--muted-foreground));
    font-family: var(--font-mono);
    font-weight: 600;
  }

  .cropper-ar-presets {
    display: flex;
    flex-wrap: wrap;
    gap: 0.375rem;
  }

  .cropper-ar-btn {
    padding: 0.25rem 0.625rem;
    border-radius: 0.25rem;
    border: 1px solid hsl(var(--border));
    font-size: 0.625rem;
    letter-spacing: 0.05em;
    font-weight: 600;
    text-transform: lowercase;
    cursor: pointer;
    transition: all 0.15s;
    background: transparent;
    color: hsl(var(--muted-foreground));
    font-family: var(--font-sans);
  }
  .cropper-ar-btn:hover {
    border-color: hsl(var(--foreground) / 0.4);
    color: hsl(var(--foreground));
  }
  .cropper-ar-btn.active {
    color: hsl(var(--pride-glow-val));
    border-color: hsl(var(--pride-glow-val) / 0.45);
    background: hsl(var(--pride-glow-val) / 0.1);
    font-weight: 700;
  }

  .cropper-footer {
    display: flex;
    align-items: center;
    justify-content: flex-end;
    gap: 0.5rem;
    border-top: 1px solid hsl(var(--border) / 0.5);
    padding-top: 0.75rem;
  }

  .cropper-btn {
    font-size: 0.6875rem;
    font-weight: 700;
    text-transform: lowercase;
    padding: 0 1rem;
    height: 2.25rem;
    border-radius: 9999px;
    cursor: pointer;
    border: 1px solid hsl(var(--border));
    font-family: var(--font-sans);
    transition: all 0.15s;
  }
  .cropper-btn:disabled { opacity: 0.5; cursor: not-allowed; }

  .cropper-btn-outline {
    background: transparent;
    color: hsl(var(--foreground));
  }
  .cropper-btn-outline:hover:not(:disabled) { background: hsl(var(--muted) / 0.5); }

  .cropper-btn-primary {
    background: hsl(var(--foreground));
    color: hsl(var(--background));
    border-color: hsl(var(--foreground));
  }
  .cropper-btn-primary:hover:not(:disabled) { opacity: 0.85; }
</style>

// src/app/favorites/_components/ImageCropperModal.tsx
'use client'

import { useState, useEffect, useRef } from 'react'
import { createPortal } from 'react-dom'
import { motion } from 'framer-motion'
import { X, ZoomIn, ZoomOut } from 'lucide-react'
import { Button } from '@/components/ui/primitives/button'
import { cn } from '@/lib/utils/utils'
import { monoFont, sansFont } from '@/styles/fonts/fonts'

export type CropAspectRatio = '3:4' | '16:9' | '1:1' | 'original'

interface ImageCropperModalProps {
	imageSrc: string
	onClose: () => void
	onCrop: (croppedDataUrl: string) => void
	defaultAspectRatio?: CropAspectRatio
}

const ASPECT_RATIO_PRESETS: { key: CropAspectRatio; label: string; ratio: number | 'original' }[] = [
	{ key: '3:4', label: '3:4 cover', ratio: 0.75 },
	{ key: '16:9', label: '16:9 screen', ratio: 16 / 9 },
	{ key: '1:1', label: '1:1 square', ratio: 1 },
	{ key: 'original', label: 'original', ratio: 'original' },
]

export function ImageCropperModal({
	imageSrc,
	onClose,
	onCrop,
	defaultAspectRatio = '3:4',
}: ImageCropperModalProps) {
	const [aspectRatio, setAspectRatio] = useState<CropAspectRatio>(defaultAspectRatio)
	const [zoom, setZoom] = useState<number>(1)
	const [offset, setOffset] = useState<{ x: number; y: number }>({ x: 0, y: 0 })
	const [imgDimensions, setImgDimensions] = useState<{ width: number; height: number } | null>(null)
	const [isLoading, setIsLoading] = useState<boolean>(true)
	const [mounted, setMounted] = useState<boolean>(false)
	const [containerSize, setContainerSize] = useState<{ width: number; height: number }>({ width: 380, height: 340 })

	const containerRef = useRef<HTMLDivElement>(null)
	const isDraggingRef = useRef<boolean>(false)
	const dragStartRef = useRef<{ x: number; y: number }>({ x: 0, y: 0 })
	const dragOffsetStartRef = useRef<{ x: number; y: number }>({ x: 0, y: 0 })
	const updateOffsetRef = useRef<(dx: number, dy: number) => void>(() => {})

	// Ensure portal is only rendered on the client
	useEffect(() => {
		setMounted(true)
		document.body.style.overflow = 'hidden'
		return () => {
			document.body.style.overflow = ''
		}
	}, [])

	// Track container size dynamically for absolute responsiveness
	useEffect(() => {
		if (!containerRef.current) return
		const observer = new ResizeObserver((entries) => {
			if (entries[0]) {
				setContainerSize({
					width: entries[0].contentRect.width,
					height: entries[0].contentRect.height,
				})
			}
		})
		observer.observe(containerRef.current)
		return () => observer.disconnect()
	}, [mounted])

	// Load image dimensions
	useEffect(() => {
		if (!imageSrc) return
		setIsLoading(true)
		const img = new Image()
		img.onload = () => {
			setImgDimensions({ width: img.naturalWidth, height: img.naturalHeight })
			setIsLoading(false)
			setZoom(1)
			setOffset({ x: 0, y: 0 })
		}
		img.src = imageSrc
	}, [imageSrc])

	// Reset zoom and pan when aspect ratio changes
	useEffect(() => {
		setZoom(1)
		setOffset({ x: 0, y: 0 })
	}, [aspectRatio])

	// Calculate aspect ratio value
	const arVal = imgDimensions
		? aspectRatio === 'original'
			? imgDimensions.width / imgDimensions.height
			: aspectRatio === '3:4'
			? 0.75
			: aspectRatio === '16:9'
			? 16 / 9
			: 1
		: 1

	// Calculate crop frame dimensions to fit inside container with padding (40px padding)
	const containerW = containerSize.width
	const containerH = containerSize.height

	const MAX_FRAME_W = containerW - 40
	const MAX_FRAME_H = containerH - 40

	let frameW = MAX_FRAME_W
	let frameH = MAX_FRAME_W / arVal

	if (frameH > MAX_FRAME_H) {
		frameH = MAX_FRAME_H
		frameW = MAX_FRAME_H * arVal
	}

	const frameX = (containerW - frameW) / 2
	const frameY = (containerH - frameH) / 2

	// Calculate base scale and image size to cover the crop frame box at zoom 1
	let baseImgWidth = 0
	let baseImgHeight = 0
	if (imgDimensions) {
		const baseScale = Math.max(frameW / imgDimensions.width, frameH / imgDimensions.height)
		baseImgWidth = imgDimensions.width * baseScale
		baseImgHeight = imgDimensions.height * baseScale
	}

	// Dynamic offset update with bounds clamping relative to the crop frame box
	useEffect(() => {
		updateOffsetRef.current = (dx: number, dy: number) => {
			if (!imgDimensions) return
			const displayedWidth = baseImgWidth * zoom
			const displayedHeight = baseImgHeight * zoom

			const maxPanX = Math.max(0, (displayedWidth - frameW) / 2)
			const maxPanY = Math.max(0, (displayedHeight - frameH) / 2)

			const startX = dragOffsetStartRef.current.x
			const startY = dragOffsetStartRef.current.y

			setOffset({
				x: Math.max(-maxPanX, Math.min(maxPanX, startX + dx)),
				y: Math.max(-maxPanY, Math.min(maxPanY, startY + dy)),
			})
		}
	}, [zoom, imgDimensions, baseImgWidth, baseImgHeight, frameW, frameH])

	// Bounds clamp when zoom or frame changes
	useEffect(() => {
		if (!imgDimensions) return
		const displayedWidth = baseImgWidth * zoom
		const displayedHeight = baseImgHeight * zoom

		const maxPanX = Math.max(0, (displayedWidth - frameW) / 2)
		const maxPanY = Math.max(0, (displayedHeight - frameH) / 2)

		setOffset((prev) => ({
			x: Math.max(-maxPanX, Math.min(maxPanX, prev.x)),
			y: Math.max(-maxPanY, Math.min(maxPanY, prev.y)),
		}))
	}, [zoom, aspectRatio, imgDimensions, baseImgWidth, baseImgHeight, frameW, frameH])

	// Mouse and touch drag handlers
	useEffect(() => {
		const handleMouseMove = (e: MouseEvent) => {
			if (!isDraggingRef.current) return
			const dx = e.clientX - dragStartRef.current.x
			const dy = e.clientY - dragStartRef.current.y
			updateOffsetRef.current(dx, dy)
		}

		const handleTouchMove = (e: TouchEvent) => {
			if (!isDraggingRef.current || e.touches.length !== 1) return
			// Prevent double scroll or rubber-banding while cropping
			e.preventDefault()
			const dx = e.touches[0].clientX - dragStartRef.current.x
			const dy = e.touches[0].clientY - dragStartRef.current.y
			updateOffsetRef.current(dx, dy)
		}

		const handleMouseUp = () => {
			isDraggingRef.current = false
		}

		window.addEventListener('mousemove', handleMouseMove)
		window.addEventListener('mouseup', handleMouseUp)
		window.addEventListener('touchmove', handleTouchMove, { passive: false })
		window.addEventListener('touchend', handleMouseUp)

		return () => {
			window.removeEventListener('mousemove', handleMouseMove)
			window.removeEventListener('mouseup', handleMouseUp)
			window.removeEventListener('touchmove', handleTouchMove)
			window.removeEventListener('touchend', handleMouseUp)
		}
	}, [])

	const handleMouseDown = (e: React.MouseEvent) => {
		e.preventDefault()
		isDraggingRef.current = true
		dragStartRef.current = { x: e.clientX, y: e.clientY }
		dragOffsetStartRef.current = { ...offset }
	}

	const handleTouchStart = (e: React.TouchEvent) => {
		if (e.touches.length === 1) {
			isDraggingRef.current = true
			dragStartRef.current = { x: e.touches[0].clientX, y: e.touches[0].clientY }
			dragOffsetStartRef.current = { ...offset }
		}
	}

	const handleWheel = (e: React.WheelEvent) => {
		e.preventDefault()
		const zoomStep = 0.05
		const newZoom = Math.max(1, Math.min(3, zoom - e.deltaY * zoomStep * 0.01))
		setZoom(parseFloat(newZoom.toFixed(2)))
	}

	const handleSave = () => {
		if (!imgDimensions || frameW === 0 || frameH === 0) return

		const canvas = document.createElement('canvas')
		const Iw = imgDimensions.width
		const Ih = imgDimensions.height

		const baseScale = Math.max(frameW / Iw, frameH / Ih)
		const s_total = baseScale * zoom

		const W_orig = frameW / s_total
		const H_orig = frameH / s_total
		const L_orig = Iw / 2 - (frameW / 2 + offset.x) / s_total
		const T_orig = Ih / 2 - (frameH / 2 + offset.y) / s_total

		const safeL = Math.max(0, Math.min(Iw - 1, L_orig))
		const safeT = Math.max(0, Math.min(Ih - 1, T_orig))
		const safeW = Math.max(1, Math.min(Iw - safeL, W_orig))
		const safeH = Math.max(1, Math.min(Ih - safeT, H_orig))

		const currentAr = safeW / safeH

		// Output resolution (max bounding box 800px)
		let targetWidth = 800
		let targetHeight = 800 / currentAr
		if (currentAr < 1) {
			targetHeight = 800
			targetWidth = 800 * currentAr
		}

		targetWidth = Math.round(targetWidth)
		targetHeight = Math.round(targetHeight)

		canvas.width = targetWidth
		canvas.height = targetHeight

		const ctx = canvas.getContext('2d')
		if (ctx) {
			ctx.imageSmoothingEnabled = true
			ctx.imageSmoothingQuality = 'high'

			const img = new Image()
			img.onload = () => {
				ctx.drawImage(img, safeL, safeT, safeW, safeH, 0, 0, targetWidth, targetHeight)
				const croppedDataUrl = canvas.toDataURL('image/jpeg', 0.85)
				onCrop(croppedDataUrl)
				onClose()
			}
			img.src = imageSrc
		}
	}

	if (!mounted) return null

	return createPortal(
		<div className="fixed inset-0 z-50 flex items-center justify-center bg-slate-950/80 backdrop-blur-sm p-4">
			{/* Backdrop click close */}
			<div className="absolute inset-0 cursor-default" onClick={onClose} />

			<motion.div
				initial={{ opacity: 0, scale: 0.95, y: 10 }}
				animate={{ opacity: 1, scale: 1, y: 0 }}
				transition={{ duration: 0.25, ease: [0.32, 0.72, 0, 1] }}
				className="relative w-full max-w-md rounded-xl border border-slate-200 dark:border-slate-800 bg-white dark:bg-slate-900 p-5 shadow-xl flex flex-col gap-4 z-10"
			>
				{/* Header */}
				<div className="flex items-center justify-between border-b border-slate-100 dark:border-slate-850 pb-3">
					<h3 className={cn(sansFont.className, 'text-sm font-bold text-slate-900 dark:text-slate-100 lowercase')}>
						crop cover image
					</h3>
					<button
						type="button"
						onClick={onClose}
						className="text-slate-400 hover:text-slate-600 dark:hover:text-slate-200 transition-colors cursor-pointer"
					>
						<X size={16} />
					</button>
				</div>

				{/* Cropping Workspace Area */}
				<div
					ref={containerRef}
					className="relative flex items-center justify-center bg-slate-900 dark:bg-slate-950 border border-slate-150 dark:border-slate-850 rounded-lg h-[340px] w-full overflow-hidden cursor-move touch-none select-none"
					onMouseDown={handleMouseDown}
					onTouchStart={handleTouchStart}
					onWheel={handleWheel}
				>
					{isLoading || !imgDimensions ? (
						<div className="flex flex-col items-center gap-2 pointer-events-none">
							<div className="h-6 w-6 animate-spin rounded-full border-2 border-[hsl(var(--pride-glow-val))] border-t-transparent" />
							<span className={cn(monoFont.className, 'text-[10px] text-slate-400 tracking-wider lowercase')}>
								loading cover...
							</span>
						</div>
					) : (
						<>
							{/* The Image (extends outside crop frame, but contained by the workspace container) */}
							<img
								src={imageSrc}
								alt="Crop source"
								className="absolute pointer-events-none select-none max-w-none max-h-none"
								style={{
									width: baseImgWidth,
									height: baseImgHeight,
									transform: `translate(${offset.x}px, ${offset.y}px) scale(${zoom})`,
									left: '50%',
									top: '50%',
									marginLeft: -baseImgWidth / 2,
									marginTop: -baseImgHeight / 2,
									transformOrigin: 'center center',
								}}
							/>

							{/* Dark semi-transparent overlays outside the centered crop frame */}
							<div
								style={{ left: 0, top: 0, width: containerW, height: frameY }}
								className="absolute bg-slate-950/60 backdrop-blur-[0.5px] pointer-events-none"
							/>
							<div
								style={{ left: 0, top: frameY + frameH, width: containerW, bottom: 0 }}
								className="absolute bg-slate-950/60 backdrop-blur-[0.5px] pointer-events-none"
							/>
							<div
								style={{ left: 0, top: frameY, width: frameX, height: frameH }}
								className="absolute bg-slate-950/60 backdrop-blur-[0.5px] pointer-events-none"
							/>
							<div
								style={{ left: frameX + frameW, top: frameY, right: 0, height: frameH }}
								className="absolute bg-slate-950/60 backdrop-blur-[0.5px] pointer-events-none"
							/>

							{/* Center Crop Frame Highlight Border & Grid */}
							<div
								style={{
									left: frameX,
									top: frameY,
									width: frameW,
									height: frameH,
								}}
								className="absolute border border-white pointer-events-none shadow-[0_0_0_1px_rgba(0,0,0,0.3)]"
							>
								{/* Grid lines inside box */}
								<div className="absolute inset-0 grid grid-cols-3 grid-rows-3 pointer-events-none opacity-50">
									<div className="border-r border-b border-white/20" />
									<div className="border-r border-b border-white/20" />
									<div className="border-b border-white/20" />
									<div className="border-r border-b border-white/20" />
									<div className="border-r border-b border-white/20" />
									<div className="border-b border-white/20" />
									<div className="border-r border-white/20" />
									<div className="border-r border-white/20" />
									<div />
								</div>
							</div>
						</>
					)}
				</div>

				{/* Controls (Aspect Ratio & Zoom) */}
				{!isLoading && imgDimensions && (
					<div className="flex flex-col gap-4 py-1">
						{/* Zoom Control */}
						<div className="flex items-center gap-3">
							<ZoomOut size={14} className="text-slate-400" />
							<input
								type="range"
								min="1"
								max="3"
								step="0.01"
								value={zoom}
								onChange={(e) => setZoom(parseFloat(e.target.value))}
								className="flex-1 h-1 bg-slate-200 dark:bg-slate-800 rounded-lg appearance-none cursor-pointer accent-[hsl(var(--pride-glow-val))]"
							/>
							<ZoomIn size={14} className="text-slate-400" />
							<span className={cn(monoFont.className, 'text-[9px] text-slate-400 w-8 text-right font-medium')}>
								{Math.round(zoom * 100)}%
							</span>
						</div>

						{/* Aspect Ratio Presets */}
						<div className="flex flex-col gap-1.5">
							<span className={cn(monoFont.className, 'text-[9px] lowercase tracking-widest text-slate-400 font-semibold')}>
								aspect ratio
							</span>
							<div className="flex flex-wrap gap-1.5">
								{ASPECT_RATIO_PRESETS.map((preset) => (
									<button
										key={preset.key}
										type="button"
										onClick={() => setAspectRatio(preset.key)}
										className={cn(
											sansFont.className,
											'px-2.5 py-1 rounded-sm border text-[10px] tracking-wide font-semibold lowercase transition-all duration-200 cursor-pointer',
											aspectRatio === preset.key
												? 'text-[hsl(var(--pride-glow-val))] border-[hsl(var(--pride-glow-val))]/45 bg-[hsl(var(--pride-glow-val))]/10 font-bold'
												: 'border-slate-200 bg-transparent text-slate-500 hover:border-slate-350 hover:text-slate-800 dark:border-slate-800 dark:text-slate-400 dark:hover:border-slate-700 dark:hover:text-slate-200'
										)}
									>
										{preset.label}
									</button>
								))}
							</div>
						</div>
					</div>
				)}

				{/* Actions Footer */}
				<div className="flex items-center justify-end gap-2 border-t border-slate-100 dark:border-slate-850 pt-3">
					<Button
						variant="outline"
						onClick={onClose}
						className="lowercase font-bold h-9 px-4 text-[11px] rounded-full"
					>
						cancel
					</Button>
					<Button
						onClick={handleSave}
						disabled={isLoading || !imgDimensions}
						className="lowercase font-bold h-9 px-4 text-[11px] rounded-full"
					>
						crop & save cover
					</Button>
				</div>
			</motion.div>
		</div>,
		document.body
	)
}
