// src/app/suggestions/page.tsx
import type { Metadata } from 'next'
import { SectionPageShell } from '@/components/layout/page-shell/SectionPageShell'
import { SuggestionsBoard } from './_components/SuggestionsBoard'

export const metadata: Metadata = {
  title: 'Suggestions | mikeblocky.com',
  description: 'A place to suggest books, manga, music, or films you think I would enjoy.'
}

export default function SuggestionsPage() {
  return (
    <SectionPageShell
      title="Suggestions"
      description="Suggest books, manga, music, or movies for me to check out next."
      currentLabel="Suggestions"
    >
      <SuggestionsBoard />
    </SectionPageShell>
  )
}

// apps/web-sveltekit/src/routes/suggestions/+page.svelte
<script lang="ts">
  import SuggestionsBoard from '$lib/components/SuggestionsBoard.svelte';
  import SeoHead from '$lib/components/SeoHead.svelte';
  import SectionPageShell from '$lib/components/SectionPageShell.svelte';

  let passcode = '';
  let isAdminMode = false;
</script>

<SeoHead
  title="Suggestions"
  path="/suggestions"
  description="A place to suggest books, manga, music, or films you think I would enjoy."
/>

<SectionPageShell
  title="Suggestions"
  description="Suggest books, manga, music, or movies for me to check out next."
  currentLabel="Interact"
  footerColor="blue"
>
  <SuggestionsBoard bind:isAdminMode bind:passcode />
</SectionPageShell>
