// src/app/zine/page.tsx
import type { Metadata } from 'next'
import { SectionPageShell } from '@/components/layout/page-shell/SectionPageShell'
import { getZines } from './_data/zines'
import { ZineLibrary } from './_components/ZineLibrary'

export const metadata: Metadata = {
	title: 'Zine | mikeblocky.com',
	description: 'Collected works presented as small page-turning books.'
}

export default function ZinePage() {
	const zines = getZines()

	return (
		<SectionPageShell
			title="Zine"
			description="Collected works arranged as handmade books."
			currentLabel="Zine"
			containerSize="3xl"
			footerColor="pink"
		>
			<ZineLibrary zines={zines} />
		</SectionPageShell>
	)
}

// apps/web-sveltekit/src/routes/zine/+page.svelte
<script lang="ts">
  import SeoHead from '$lib/components/SeoHead.svelte';
  import ZineBookshelf from '$lib/components/ZineBookshelf.svelte';
  import SectionPageShell from '$lib/components/SectionPageShell.svelte';

  export let data;
</script>

<SeoHead title="zine" path="/zine" description="Collected works presented as small page-turning books." />

<SectionPageShell
  title="Zine"
  description="Collected works arranged as handmade books."
  currentLabel="Zine"
  footerColor="blue"
>
  <ZineBookshelf zines={data.zines} />
</SectionPageShell>
